### ISSUE TITLE
Put "Mark all as read" button in footer

### ISSUE THREAD

**Issue by Keith94** [freaktechnik/advanced-github-notifier#10]
I think the "Mark as read" should be moved outside the actual panel content if possible, perhaps add it to the footer beside "Open notifications page", which is similar to the dropdown menu of the downloads panel footer:

![image](https://cloud.githubusercontent.com/assets/5490615/19709785/238ae1aa-9ade-11e6-9b2f-1b8e011c29ad.png)

It could be represented with a checkmark icon rather than text. Just an idea.

**Comment by Keith94** [comment]
I have no idea of the current limitations of WebExtensions API or anything like that, however I hope something like that is still possible.

**Comment by freaktechnik** [comment]
I could do that but it's not how the footer in such panels has been used. I decided to use a list item for mark all as read due to how the history panel works.
