### ISSUE TITLE
Improve UI around multiple accounts

### ISSUE THREAD

**Issue by domoritz** [freaktechnik/advanced-github-notifier#104]
First, thanks for making this awesome addon! this is a small nitpick but I think the UI around showing multiple accounts could be improved. Right now it's visually hard to see that there is an account and that there could be more than once. I wanted to disable desktop notifications and was super confused why there are two checkboxes.

I propose to
* move all global options above the accounts
* Add a header like "Accounts"
* Create a visual block for the account so that it's clear that the controls belong to it

<img width="658" alt="screen shot 2019-02-10 at 11 12 11" src="https://user-images.githubusercontent.com/589034/52538221-d65cf680-2d24-11e9-8b5b-7121d7b3bf1c.png">

**Comment by freaktechnik** [comment]
@all-contributors add @domoritz for ideas
