### ISSUE TITLE
Put repository name on a new line

### ISSUE THREAD

**Issue by Keith94** [freaktechnik/advanced-github-notifier#11]
In the panel, can you move the repo name underneath or above the name of the issue/pull request etc, rather than beside it? Currently having the name beside it can make the panel seem too wide.

**Comment by freaktechnik** [comment]
I'm using the native styles for the panel and am already hacking them a lot to just get it to look like it does. I know that the panel can get super long and I'll have to think of a solution for that in #7.

**Comment by Keith94** [comment]
Ahh yeah, it looks especially weird when the text starts to wrap onto a new line:

![firefox_2016-10-26_13-11-38](https://cloud.githubusercontent.com/assets/5490615/19744334/f679e0d6-9b81-11e6-8d21-fc94bb110a36.png)

**Comment by freaktechnik** [comment]
Yeah, that's getting handled in #7. Are you ok with calling it a dupe for now? Feel free to re-open once I mark that as fixed and it is still an issue.
