### ISSUE TITLE
Option to disable badge

### ISSUE THREAD

**Issue by stoically** [freaktechnik/advanced-github-notifier#114]
Hey there,

thanks for your work on AGN, it just works!

Something I'd like to see is a snooze button, which disables notifications (and maybe adds Z as badge text or something). That'd be great.

**Comment by freaktechnik** [comment]
You can use the DND feature of Firefox or of your OS to snooze notifications. I don't think notification settings should be part of an extension apart from does the extension show notifications at all yes/no.

**Comment by stoically** [comment]
Maybe I'm blind, but it seems like the DND for notifications in Firefox is gone. The OS snooze might be a solution. But I don't use actual system notifications, just the browser action badge as notifier, so actual notifications settings unfortunately don't help with that.

The reason I'm asking is, that I sometimes find myself in the middle of some work, just to get distracted by the badge, so having a way of disabling it when doing work would be handy. Does that make more sense?

**Comment by freaktechnik** [comment]
Ah, you want to disable the badge, that I'm fine with.

**Comment by tooomm** [comment]
Just came here to request that.

There is already a `Notification pop up [ ]` option in setting.
Having a `Badge [ ]` one too would be awesome! :)

**Comment by freaktechnik** [comment]
This will be in 1.7.0.

**Comment by stoically** [comment]
Works well, thanks. It's even possible to disable the badge via the context menu of the toolbar icon, which is nice!
