### ISSUE TITLE
Adjust toolbarbutton id value

### ISSUE THREAD

**Issue by Keith94** [freaktechnik/advanced-github-notifier#12]
Currently the id for the toolbar button seems to be `_8d4b86c5-64bf-4780-b029-0112386735ab_-browser-action` (via DOMi).

So is it possible to change the id to something that's easier to identify? Like `advancedGithubNotifier-button` for example. Thanks.

**Comment by freaktechnik** [comment]
Nope, that is completely in tge handd of Firefox for WebExtensions afaik.

**Comment by freaktechnik** [comment]
It is even possible that every Firefox profile with the extension would have a different id for the button, I'm not sure which internal ID it is based on.

**Comment by Keith94** [comment]
Hmm, it seems to share the same id within two different profiles that I tested just now...

It's not really a big issue, but would look more consistent with other button ids and such imo. :p

**Comment by Keith94** [comment]
I saw the [webext version of uBlock Origin](https://github.com/gorhill/uBlock/releases/tag/1.9.17b0) seems to have a "correct" button id (displays as `ublock0_raymondhill_net-browser-action`) when installed in the browser... can you tell me if it's different somehow?

**Comment by freaktechnik** [comment]
it probably has a specific ID set for legacy reasons, as it was upgraded from a bootstrapped extension. And apparently that had a human-readable ID, so that's the ID Firefox has to use.
