### ISSUE TITLE
Extension gets confused at Firefox startup only

### ISSUE THREAD

**Issue by svarshavchik** [freaktechnik/advanced-github-notifier#124]
Started seeing this behavior on Linux, firefox-71.0-8.npgo.fc31.x86_64.

Version 1.5.0 of the extension.

I am logged into github, in Firefox.

Each time Firefox starts, the extension thinks it can't sign into github, and, has a big red question mark on top of it.

In the extension's addons page, under "Preferences", the github account is described as:

undefined Github

If I:

1) click "Log Out". This removes the "undefined Github" account row.

2) click "Add Account"

The 2nd click does not add anything on the "Permissions" change, but the extension does something, and it thinks it's now logged in. The big red question mark disappears, and the extension's "Show All Notifications" option opens my github notifications page.

3) Refresh (F5)

Hitting "Refresh" at this point now shows my github account on the permissions page:

svarshavchik github <bunch of whitespace> Show desktop notifications [v] [Log Out]

And the extension is happy again, until the next time I restart Firefox.

I removed and reinstalled the extension, this does not fix this behavior.

Other extensions in use that might be involved: uBlock origin, also the network proxy is privoxy. But the extension works normally, once the configured github account is removed and added.

**Comment by freaktechnik** [comment]
That indicates to me that the extension can not communicate with GitHub when it starts, since the first order of business for it is to verify it can still read the notifications for all github accounts and then download the data.

Also, sorry for not responding at all for a long time.

**Comment by svarshavchik** [comment]
This problem stopped occuring after the last Firefox update from Fedora. This seemed to affect only a particular Firefox build. Searching around found https://bugzilla.redhat.com/show_bug.cgi?id=1779570 that reported problems with other extensions on the same Firefox build; that were resolved in a subsequent Firefox update.

**Comment by freaktechnik** [comment]
:+1:
