### ISSUE TITLE
Doesn't show notifications from private repos

### ISSUE THREAD

**Issue by sergioc** [freaktechnik/advanced-github-notifier#17]
When opening the AGN menu, it only shows notifications from public repos, even if there's more from private repos.

E.g. right now I have 9 notifications and it only shows 1 in the menu. Seems like it'll only show notifications from public repos, since the other 8 notifications are in private repos.

**Comment by freaktechnik** [comment]
The extension indeed doesn't have sufficient privileges yet to show notifications for private repos. IT currently only requests the notifications scope, which doesn't give enough information to display a meaningful notification. In the future the extension will request the repo scope.

I'll have to look into how to best upgrade existing authorizations.

**Comment by freaktechnik** [comment]
This should be solved with 1.1.0pre5: https://addons.mozilla.org/en-US/firefox/addon/advanced-github-notifier/versions/beta?page=1#version-1.1.0pre5
