### ISSUE TITLE
Unsubscribe from issues directly from AGN menu

### ISSUE THREAD

**Issue by sergioc** [freaktechnik/advanced-github-notifier#18]
Unsubscribe from issues directly from the AGN menu, similarly to how you do it from https://github.com/notifications

**Comment by freaktechnik** [comment]
I'll do this as soon as I can use the context menu - just like I'll add a mark as read option for individual notifications.

**Comment by sergioc** [comment]
Does that mean you're planing to implement this via a context menu on top of the AGN menu?

**Comment by freaktechnik** [comment]
Yes.

**Comment by sergioc** [comment]
How about just mimicking the GH UI, and allow doing it in 1 click?

**Comment by freaktechnik** [comment]
Mostly due to space reasons but also because I don't want to deal with the style implications. I'm currently using native styles for the popup and would have to do a lot of acrobatics to make it work cross-platform.

I also think that hitting the targets would be too small for the current size of an item - an issue the github UI doesn't have.

**Comment by sergioc** [comment]
That significantly kills the experience for me. I'm using AGN as a shortcut to managing notifications as simply or simpler than in GH UIs. Currently all that the menu does for me that the other GH Notifier extension doesn't do is help avoid the need to open the Notifications page.

**Comment by sergioc** [comment]
How about adding `unsubscribe` / mark as read` text links on hover?

**Comment by freaktechnik** [comment]
I see that it doesn't necessarily remove a click for marking a notification as read. That was never the primary goal.

I already have way too many issues with the styling as is and I don't want to use a different style. I also don't see how having text links would solve the size issues, as it'd make it harder to actually open the notification and not significantly increase the height of the click area, which is the main problem in my opinion.
