### ISSUE TITLE
Firefox: Showing ?, no popup

### ISSUE THREAD

**Issue by peter-kehl** [freaktechnik/advanced-github-notifier#183]
On Firefox 81.0 for Linux.

The icon shows a question mark: 
![image](https://user-images.githubusercontent.com/4270240/95113838-e72b5e80-06f7-11eb-8308-3f794d472738.png)

I am logged on to GitHub, and I do have 6 notifications:
![image](https://user-images.githubusercontent.com/4270240/95113913-00cca600-06f8-11eb-84fa-f3523dc389e5.png)

Clicking at the icon doesn't show any popup, but it goes to about:addons for this add-on.

**Comment by freaktechnik** [comment]
You have to authenticate the extension for it to be able to load your notifications.

**Comment by peter-kehl** [comment]
Thank you.
While that did work, I don't understand why it would be necessary.
The addon's docs at about:addons say "This permission only has to be
granted on organizations with private repositories that you need
notifications for.".

However, I didn't have any private repo notifications. All my 6
notifications came from public repos.

**Comment by freaktechnik** [comment]
It only needs the "repo" permission for private repos. It still needs the notifications one for public ones (which is what the "GitHub (no private repos)" login type asks for). The extension interacts with the GitHub API and as such is not relying on the session of your browser like some other extensions. This also allows getting notifications for multiple accounts, among other things.
