### ISSUE TITLE
Link to "All notifications page" instead of "Notifications page.

### ISSUE THREAD

**Issue by sergioc** [freaktechnik/advanced-github-notifier#19]
With AGN, a trip to https://github.com/notifications becomes less of a need or is not needed at all, since the menu shows the same notifications.

A link to https://github.com/notifications?all=1 thus becomes more valuable, since it show ALL current and past notifications.

**Comment by Keith94** [comment]
@freaktechnik Can this be made optional? I prefer to see only current notifications.
