### ISSUE TITLE
Draft PR's don't use the grey icon

### ISSUE THREAD

**Issue by tooomm** [freaktechnik/advanced-github-notifier#205]
Notifications for open, closed and merged PR's show their special icons.
Same like open and closed issues use different ones, too.

Draft PR's are not supported yet.

**Comment by tooomm** [comment]
Thanks for looking into that and adding a grey PR logo for `Draft PR`'s, it works!

The exact colour can be hard to spot though, it's pretty dark.
Did you try a bit lighter version as well? I guess the icon is to small for using outlines only?

**Comment by freaktechnik** [comment]
The extension currently uses the exact colors github uses (or at least used at time of implementation of features, the red and green might be slightly off since dark mode became a thing).

**Comment by tooomm** [comment]
I do not use dark mode or any other theme for Firefox - all default.

The used colour might be the accurate representation of what GitHub uses, the colour impression when displayed as small is different though.
On the GitHub page it's easier to recognizing PR types by their coloured icons.
In the extension however, the grey seems kinda dark and when looked at it in isolation (without having red closed PR's or green open PR's around which use the same icon type) you can not be sure that it's grey for "draft".
One could easily mix it up with a generic icon for a pull request as its "dark" (=generic black) than "grey".

That's why I asked if you tried a bit lighter grey as well. Maybe that's easier to correctly connect with "draft" right away.

**Comment by tooomm** [comment]
Finally got around to take some screenshots. I can't help it, but it looks super difficult to differentiate easily/quickly for me...
On GitHub itself it's a bit easier as the icon is bigger - still not perfect.

- Your addon:
![addon](https://user-images.githubusercontent.com/9874850/107283421-ad2ee800-6a5c-11eb-9c16-58020f564bdc.png)

- GitHub notification page:
![github](https://user-images.githubusercontent.com/9874850/107283431-b1f39c00-6a5c-11eb-9c67-1f8499879fbb.png)


I doubts it's my monitor as I use an Eizo with PVA panel.
