### ISSUE TITLE
Choose the footer button target

### ISSUE THREAD

**Issue by Keith94** [freaktechnik/advanced-github-notifier#22]
Add option to open "Unread", "Participating", or "All" notifications when clicking footer button. See #19

**Comment by freaktechnik** [comment]
This is in 1.2.0 (available as beta for now): https://addons.mozilla.org/en-US/firefox/addon/advanced-github-notifier/versions/beta?page=1#version-1.2.0pre1

**Comment by freaktechnik** [comment]
1.2.0 is now released on amo. You can now select the footer target.
