### ISSUE TITLE
Open all notifications at once

### ISSUE THREAD

**Issue by UtechtDustin** [freaktechnik/advanced-github-notifier#242]
I love this browser plugin, but normally i open all notifications an check one after the other.
That also means i have to click quiet often to open all notifications. I would love if you could add a feature to open all notifications at once.

**Comment by tooomm** [comment]
I miss this ability as well!
However, this is a duplicate of https://github.com/freaktechnik/advanced-github-notifier/issues/58.

The conversation there is mostly about a misunderstanding, but the feature request is the same. :)

**Comment by freaktechnik** [comment]
Thanks for pointing it out!
Closing as duplicate of #58
