### ISSUE TITLE
Give option to display only open review-requested 

### ISSUE THREAD

**Issue by vimalk78** [freaktechnik/advanced-github-notifier#248]
**Is your feature request related to a problem? Please describe.**
Give option to display only open review-requested 
https://github.com/pulls/review-requested

**Describe the solution you'd like**
When i click the icon, the pop up should sow results from https://github.com/pulls/review-requested

**Describe alternatives you've considered**
none

**Additional context**
want to make it easier for me to get notified of review requested, among various other type of notifications

**Comment by freaktechnik** [comment]
This is a duplicate of #35
