### ISSUE TITLE
Linking to issue comment or event

### ISSUE THREAD

**Issue by Keith94** [freaktechnik/advanced-github-notifier#30]
When I click on an issue in the panel, can it automatically take me to the new comment or event that was posted, without having to scroll down? For example:

`https://github.com/ParticleCore/Iridium/issues/23#event-1213342840`
`https://github.com/Codeusa/Borderless-Gaming/issues/343#issuecomment-323610791`

advanced-github-notifier seems to not open the full url including the `#` character.

**Comment by freaktechnik** [comment]
Correct. It currently does not move you to the last unread item in a thread.

**Comment by Keith94** [comment]
I see, it would be a great feature to have. :)
