### ISSUE TITLE
popup no longer opens

### ISSUE THREAD

**Issue by phit** [freaktechnik/advanced-github-notifier#32]
Clicking the addon icon stopped working for me with the recent Nightly update, 

debug console output when clicking the icon:

![image](https://user-images.githubusercontent.com/2097483/30180335-dabff9fc-940f-11e7-9ed8-5f78fdb1494b.png)

Running 1.2.1 with Nightly 57.0a1 (2017-09-07) (64-bit) on Windows 10

Thanks, let me know if you need anything else.

**Comment by phit** [comment]
I did multiple times, weird part is it worked yesterday. Gonna do some more testing, maybe some other addon update is breaking it.

**Comment by freaktechnik** [comment]
Oh, one thing to do would be to try with out of process webextensions disabled - especially if you are on windows. Try the `extensions.webextensions.remote` and `extensions.webextensions.protocol.remote` prefs.

**Comment by phit** [comment]
Setting `extensions.webextensions.remote` to false fixed it! Thanks a lot.

**Comment by freaktechnik** [comment]
And you could open the auth dialog afterward? i.e. did you have a `?` badge?

**Comment by phit** [comment]
I was still logged in, I disabled the setting, restarted Firefox, then after clicking the icon a window popped up briefly probably auth dialog refreshing, disappeared and now the question mark is gone and notifications show up fine.

Just to test, went to the addon options and logged out, question mark came up again, clicking it opened the login page and I could login again.

**Comment by freaktechnik** [comment]
thanks, I'll try to track this with Firefox, since this seems like a platform bug.

**Comment by freaktechnik** [comment]
(Keeping this open until I have reproduced it & reported a bug)

**Comment by freaktechnik** [comment]
I have not been able to reproduce this. Either way, if this occurs to you again (with the same errors), please raise a bug on bugzilla.mozilla.org in the WebExtensions:Untriaged component.

**Comment by freaktechnik** [comment]
Actually, if it still happens I have just had a conversation with a developer working on some issues with the identity api not working as it should.
