### ISSUE TITLE
White icon for dark mode

### ISSUE THREAD

**Issue by Keith94** [freaktechnik/advanced-github-notifier#33]
The current toolbar button is hard to see when using a dark theme in Firefox

![image](https://user-images.githubusercontent.com/5490615/30719674-31cdde16-9ed9-11e7-8530-f779eaeeaf1d.png)

Maybe the outline/background could be filled with white, or add an inverted variant of the icon?
Something like: https://github.com/fluidicon.png

**Comment by Keith94** [comment]
Oops, didn't notice it was implemented here eedc9dd. I'll wait for a release version, then

**Comment by freaktechnik** [comment]
Probably won't be in a release version for a bit, because theme_icons has an issue with using the light version in the default theme, which is wrong.
