### ISSUE TITLE
GH Action notifs don't mark as read from opening them

### ISSUE THREAD

**Issue by freaktechnik** [freaktechnik/advanced-github-notifier#332]
Due to the subject being super vague we can't properly mark them as read. Same problem as security notifs I think.

**Comment by freaktechnik** [comment]
https://github.com/freaktechnik/advanced-github-notifier/commit/0368d31559cba8ada02cb2f65cb4af7269e43c2f fixed this but referenced the wrong issue.

**Comment by tooomm** [comment]
I still have the same issue.

Clicking marks them as read in your extension, but not on GitHub. With the next fetch it's recognized as new notification and shows up again.

**Comment by tooomm** [comment]
Any updates on this?
