### ISSUE TITLE
Add option to move "Show All Notifications" button to the top of the popup

### ISSUE THREAD

**Issue by silverwings15** [freaktechnik/advanced-github-notifier#440]
**Is your feature request related to a problem? Please describe.**
When there are too many notifications (over 600 in my case), you have to scroll all the way to the bottom to find the Show All Notifications button

**Describe the solution you'd like**
If possible, please implement an option to have the button placed at the top of the notifications popup, rather than at the bottom.

**Comment by freaktechnik** [comment]
My plan for this specific problem is #63 - so the button would always be visible and only the area above it would scroll. Sadly with the upcoming change to mv3 I probably won't really have time to address the user interface in the next little while, still.

**Comment by silverwings15** [comment]
yeah that would be a great solution. nice to know it's in the works, even if we have some way to go yet. thank you!
