### ISSUE TITLE
Feature Request: Compatibility with Chrome Browser

### ISSUE THREAD

**Issue by euxx** [freaktechnik/advanced-github-notifier#509]
Hi, thanks for your hard work on this extension. It's quite convenient for everyday use.

I was wondering if there are any plans for making this extension compatible with the Chrome browser? I believe this would benefit many Chrome users.

I tried to find similar on Chrome.  The most similar one I found is https://github.com/sindresorhus/notifier-for-github ，but it can't direct access to the notifications.

So just to see if there's possible to adapt to Chrome.

**Comment by freaktechnik** [comment]
Duplicate of #49
