### ISSUE TITLE
options on settings page are tiny

### ISSUE THREAD

**Issue by tooomm** [freaktechnik/advanced-github-notifier#59]
I almost missed the available options, because they are presented that small at the bottom. :)

**Comment by freaktechnik** [comment]
I can't really change where the options are shown.

**Comment by tooomm** [comment]
<sub>Well, a lot of extensions use a separate window for their options.</sub>
But you could just change *how* they are shown, at least make them appear bigger for example. 👍 

You might want to have a look at this Thunderbird extension: https://github.com/mkiol/GNotifier
I'm sure there are other examples too...

![settings](https://user-images.githubusercontent.com/9874850/32699640-75ce9570-c7b9-11e7-90ef-d078debaeb96.png)

**Comment by freaktechnik** [comment]
The actual size they appear is based on browser settings. Note that the settings interface for webextensions and thunderbird is very different for the developer and how they can style things.

(I don't want to have a separate settings page, I don't see the point of it for the little bit of settings this extension has)

**Comment by freaktechnik** [comment]
Also, if an extension has an [Options] button in the list and it opens the details page there are always options below the info.

**Comment by tooomm** [comment]
>The actual size they appear is based on browser settings. Note that the settings interface for webextensions and thunderbird is very different for the developer and how they can style things.

Too bad the default displaying size that small. The way addons got handled earlier was way more user friendly regarding this type of options.

Is there a way to change this brower setting? Any clue?


>(I don't want to have a separate settings page, I don't see the point of it for the little bit of settings this extension has)

That is totally reasonable, I think the same by the way.
I just casually mentioned it because you argued it wouldn't be possible to have other locations to show settings.

**Comment by freaktechnik** [comment]
> Is there a way to change this brower setting? Any clue?

I'm not sure if this correlates to your font size you set in your browser, probably shouldn't since it's treated as "browser UI", though those styles are super wonky...

**Comment by tooomm** [comment]
While checking all my extensions... the old `Legacy` ones are good, but I found another one with the same issue and tiny size.

A future ff update might improve it hopefully, or maybe there is a `about:config` setting?

**Comment by freaktechnik** [comment]
`about:config` surely can't affect size here, since it's purely CSS based.

**Comment by tooomm** [comment]
So we have to wait and hope... 😆

**Comment by tooomm** [comment]
Actually, you might want to look at this...

The `Refined GitHub` addon had the same displaying problem with tiny text etc.
https://addons.mozilla.org/en-US/firefox/addon/refined-github-/
https://github.com/sindresorhus/refined-github

I updated today to 17.12.29.1450 and options are displayed considerably bigger!

Looking at their repo, this might be the relevant change: https://github.com/sindresorhus/refined-github/pull/927

**Comment by freaktechnik** [comment]
That is essentially what I am doing, just that I am using an officially supported path for it. For all I know the text should be far from tiny, though it is not huge like other parts of the Firefox in-content UI are.

**Comment by tooomm** [comment]
>That is essentially what I am doing

Well, there is still a essential difference somehow...

To demonstrate you I reinstalled the older version on FF 57.0.3:
- Version 17.12.28.1449
![1449](https://user-images.githubusercontent.com/9874850/34453769-acdb5594-ed5c-11e7-9336-0a3cd1d97fa1.png)
- Version 17.12.29.1450
![1450](https://user-images.githubusercontent.com/9874850/34453771-afabbaf2-ed5c-11e7-8a0c-60297dae6a23.png)

Try it for yourself, the screens don't really make it that clear I guess.
https://addons.mozilla.org/en-US/firefox/addon/refined-github-/versions/

In comparison the "Advancded GitHub Notifier 1.2.1" settings look like this:
![advanced github notifier 1 2 1](https://user-images.githubusercontent.com/9874850/34453819-70fb8688-ed5d-11e7-9084-9625b8f9f1fa.png)
Your addon suffers a very similar problem!

>For all I know the text should be far from tiny

Call it whatever you want, the settings are displayed too small which is bad. :)
I can easily imagine that they are very hard to use on a modern high-res touch device like the Surface Pro.

I only try to help in pointing things out and giving hints on how others dealt with it. Maybe the linked PR wasn't the reason for the great new way they use to display their settings... it was just a guess.
Anyway, they solved it and the result is a charm.

**Comment by fregante** [comment]
If you use https://github.com/fregante/webext-base-css (<1kb) you'll also automatically get dark mode support.
