### ISSUE TITLE
Not seeing notifications on Firefox 59

### ISSUE THREAD

**Issue by meshy** [freaktechnik/advanced-github-notifier#61]
I have a single unread notification on github, but the plugin doesn't show that I have any notifications.

I've just installed this for the first time, and noticed one other thing when logging into github (I don't know if this is relevant): the final redirect from github to `localhost` was unable to display anything, and just showed an "unable to connect" page.

I think I am now logged in, however, because when I "log out" in the addon-page, clicking on the icon logs me back in again instantly.

**Comment by freaktechnik** [comment]
Yeah, the first login is broken somehow, but that seems to be a Firefox API issue.

What kind of notification is pending? Could you verify that the network request to api.github.com/notifications succeeds in the browser toolbox (in the web developer submenu)?

**Comment by freaktechnik** [comment]
See https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox

**Comment by meshy** [comment]
I think I was simply being impatient, sorry. Please forgive me. The notifications are now appearing, but there was simply more of a delay than I had expected. I think it updated after around a minute.

Thank you for the very quick response!

**Comment by freaktechnik** [comment]
Yeah, the update interval is in the best case one minute (at least as long as github reports that as the desired polling interval), and in the worst case however many calls can be fit in your remaining API budget (mainly important when running multiple browser instances logged in to the same account on the same network)

**Comment by meshy** [comment]
I feel daft to open this again now, but I'm afraid I'm still seeing issues. I've had my browser open for quite a long time now, and I'm still not seeing notifications (on pull-requests, for what it's worth).

I've opened the addon debugger, and I'm seeing that requests to `https://api.github.com/notifications` are getting a `304 Not Modified` response.

I'm a little confused about this, because I see the same thing even when I follow one of the links on the notification page (so the notifications should have changed).

Is there further information I could provide to help debug this?

**Comment by tooomm** [comment]
I want to jump in here... the notification icon displays updates just fine but I don't see browser notifications anymore!
I used to see them which was awesome, but they are gone now since several days.

Running FF56 on Windows 10.

**Comment by meshy** [comment]
Further information... I saw a red bubble for that comment, so perhaps there's some difference in the handling of pull-requests and comments.

I should have mentioned that I've turned off system notifications, and that I'm on Linux.

**Comment by meshy** [comment]
Ooh, another ideal. Perhaps the issue lies in the fact that the pull-requests I've been getting notifications for are from a private repo on an organisation.

I'll check the permissions on the access key...

**Comment by meshy** [comment]
Ok, that's what it was. Closing again! Sorry for the noise!

![https://raw.githubusercontent.com/meshy/gifs/master/cat-facepalm.gif](https://raw.githubusercontent.com/meshy/gifs/master/cat-facepalm.gif)

**Comment by freaktechnik** [comment]
@tooomm if you do have this issue, could you elaborate what kind of notifications you have pending that the extension is not showing? I know that there is an issue with repo invites in the current release, for example.
