### ISSUE TITLE
Permissions required are too much

### ISSUE THREAD

**Issue by raskchanky** [freaktechnik/advanced-github-notifier#72]
I installed this today and during the oauth dance with GH was informed that the plugin wanted full access to all public and private repositories.  I don't understand why a notifications plugin requires that, especially when there's an oauth setting specifically for `notifications`.  I want to use this plugin, but I'm not going to authorize it to access every repo in my account.

**Comment by meshy** [comment]
Github does not offer very fine grained permissions. I'm not 100% sure, but I imagine this is related.

See https://github.com/dear-github/dear-github/issues/113

**Comment by raskchanky** [comment]
Here is a screenshot of the current permissions available:

![screen shot 2017-12-13 at 9 33 54 am](https://user-images.githubusercontent.com/947/33953133-d9a02c16-dfe8-11e7-8af6-aca4f607147e.png)

Perhaps that's not as fine grained as it could be, but I have to imagine it's sufficient for a plugin of this nature.  There's even a scope specifically for `notifications`.

**Comment by meshy** [comment]
`notifications` looks pretty reasonable, actually!

**Comment by meshy** [comment]
I'm feeling in the dark here, but [perhaps this is the line that needs to change](https://github.com/freaktechnik/advanced-github-notifier/blob/c9dfd376d89f63265a9bfe9fd9e9f38126dfbcb4/scripts/github.js#L47).

**Comment by freaktechnik** [comment]
It needs read permission for private repos to show meaningful notifications for those. I'm thinking about adding a way to only request the notification permission for people who only use GitHub for public code.

Sadly I can't request read:repo or similar to only get read rights for private repositories in addition to notifications (repo superseeds notifications as a permission).

**Comment by freaktechnik** [comment]
This should be fixed now and will be fixed when OAuth is re-enabled, too, since you can choose a "light" oauth path.
