### ISSUE TITLE
OAuth is aborted prelimiarily

### ISSUE THREAD

**Issue by Acid-Crash** [freaktechnik/advanced-github-notifier#80]
Today extension stopper working. Button icon stuck with "?". Login icon in Settings is inactive.
Win 10x64 FF59

**Comment by freaktechnik** [comment]
This is on the release version (1.2.x)? Clicking the button does not open the OAuth window and you are not logged in to a GitHub account that has already granted the rights? Disabling and re-enabling the extension didn't fix it?

**Comment by Acid-Crash** [comment]
Yes, this is on 1.2.1, I am logged to GitHub. The Button in settings looks like this
![github](https://user-images.githubusercontent.com/32600318/37492961-ff1589d0-28ab-11e8-9434-9a9f02558963.png)
Oauth window didn't show. Reinstalled the extension, the issue is still there.
I believe this happened after I tried to log out in the first place.

UPD. Managed to solve it after deleting GitHub cookies and extension.
Still not sure if this is normal...

**Comment by freaktechnik** [comment]
If you ever encounter this again, I'd encourage you to open the browser console and look for errors when you try to start authentication. See https://developer.mozilla.org/en-US/docs/Tools/Browser_Console for info on the browser console.

Sorry for the weird behavior, I'd love to fix that :S

**Comment by Acid-Crash** [comment]
Here is console log (reinstalled app + clicked on toolbar button, no OAuth window). 
![console](https://user-images.githubusercontent.com/32600318/37494390-4727d872-28b1-11e8-9e8f-9d58dc360760.png)

**Comment by freaktechnik** [comment]
Seems like you revoked the application access via your github account or when it requested it first time. I am not sure how you can change that, but I'll change this bug to improving the error in that case.

**Comment by gluons** [comment]
Me too.

![capture](https://user-images.githubusercontent.com/4688092/37551954-81195862-29dd-11e8-8240-7251dba8c474.PNG)

I see `An error occurred during authorization: The user has denied your application access..` error in log.

![capture](https://user-images.githubusercontent.com/4688092/37551942-4f493758-29dd-11e8-946e-9011979a64d2.PNG)

But my account already connected with [Advanced GitHub Notifier](https://github.com/login/oauth/authorize?client_id=83c8d2ca9d0cb5061af7&scope=repo) app.

![screenshot-2018-3-17 build software better together](https://user-images.githubusercontent.com/4688092/37551965-bcb6300c-29dd-11e8-80cc-1c84a389e706.png)

**Comment by freaktechnik** [comment]
I wonder if this is a platform issue, since that error would happen when you close or otherwise abort the login dialog.

**Comment by gluons** [comment]
I try uninstall and reinstall but it still doesn't help.

What I can help you to solve this issue? Life without this add-on is hard. 😢

**Comment by freaktechnik** [comment]
Maybe try revoking access or logging out from GitHub?

**Comment by gluons** [comment]
Oh! Look like `Logout -> Click on add-on icon -> Login on popup` works!

![capture](https://user-images.githubusercontent.com/4688092/37555555-9f4ab16c-2a1b-11e8-95f2-c19688ef30c5.PNG)

**Comment by freaktechnik** [comment]
So something going wrong when authing and already logged in :S

**Comment by sid-kap** [comment]
Re-logging in works, but I'm getting this error every time I open the browser.

**Comment by iamed2** [comment]
Yep, same with me.

**Comment by robkorv** [comment]
I have this to... but I can't use the logout button. It's grayed-out. Where can I find the login cookie that I have to delete to logout?

**Comment by freaktechnik** [comment]
The work around is to log out of GitHub, not the extension. Also, if anyone has a pointer as to what could be going wrong here I'd really appreciate it. I am currently using 1.3.0 (the upcoming version that I should really finish) and don't have any authentication issues, but I refactored a lot of the code around authentication for it. Sadly you can not easily try 1.3.0 anymore.

**Comment by gonzalo-trenco** [comment]
Hi @freaktechnik! I've read the issues list and saw a workaround which pretty much consists in logout + clear site cookies, but it doesn't seem to be working for me.

For giving a little context:
 - Yes, I've organization private repositories
 - I also have Two-Factor enabled

Any insights?

**Comment by freaktechnik** [comment]
Good news: I can now reproduce this.
Bad news: it's on 1.3.0 and looks like a Firefox Platform issue :(

**Comment by freaktechnik** [comment]
Update: this is arguably a GitHub bug. They auto-deny HEAD requests to the authorization endpoint. And Firefox checks if it even needs to authorize by sending a HEAD request to it...

I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1450565 for Firefox to disable this behavior and contacted GitHub about the change.

I'm torn what the best work around would be, probably to allow personal access tokens as login method.

**Comment by iamed2** [comment]
Personal access tokens would probably be the easiest way to get around this, and it seems to be what similar extensions do.

**Comment by freaktechnik** [comment]
GitHub asserts that HEAD requests are not officially supported in their OAuth protocol, thus it is something I should fix in my flow. (HEAD requests only should behave like a GET request, they don't have to).

So the OAuth flow will probably stay broken for quite some time :(

**Comment by iamed2** [comment]
Thanks!!

**Comment by freaktechnik** [comment]
v1.4.0 has just been signed and enables OAuth again in Firefox versions where this issue is fixed.

**Comment by freaktechnik** [comment]
@sid-kap if OAuth is a disabled option it means your Firefoy version is not able to successfully OAuth with Github.

The data retention issue sounds like your profile data storage may be broken and changes not persisted. Have you tried with a different Firefox profile? Alternatively, check the Browser Error console right after opening Firefox, so you can see errors that could have occurred during startup.

**Comment by freaktechnik** [comment]
@sid-kap you can inspect the stored data in your Firefox profile in the "browser-extension-data" directory and then the sub-directory for this extension ("{8d4b86c5-64bf-4780-b029-0112386735ab}"). The storage.js file there should contain a key named `github.comXXXXXX_token` if you are authorized and it is properly saved.

The managed storage manifest is for pre-configuration of enterprise instances, so that's pretty much expected that it wouldn't be found.

You can still add/switch profiles in recent Firefox versions, either by adding -p when launching or on about:profiles.

**Comment by sid-kap** [comment]
Thanks for the tips! 

It somehow started working for me! (The extension loaded my credentials properly just now, and everything looks correct in the `storage.js` file.) At least now I know where to look if it stops working again, though.
