### ISSUE TITLE
[Feature] Integration with VivaldiFox

### ISSUE THREAD

**Issue by Depau** [freaktechnik/advanced-github-notifier#81]
Hello,
I'm a [VivaldiFox](https://github.com/nt1m/vivaldi-fox) user — an extension that changes Firefox's UI color based on the `theme-color` value specified by the website (like on Chrome for Android). I'm noticing, though, that while Firefox's toolbar icons adapt and switch to a lighter/darker version based on the toolbar background color, this extension's icon does not.

Some screenshots:

![screenshot from 2018-03-18 16-25-42](https://user-images.githubusercontent.com/1151321/37567591-7cfd250a-2ac9-11e8-9105-521e1a5ca339.png)
Dark theme

![screenshot from 2018-03-18 16-26-27](https://user-images.githubusercontent.com/1151321/37567594-88242a46-2ac9-11e8-979d-2c71996bbbf0.png)
Light theme

**Comment by freaktechnik** [comment]
@nt1m as far as I know I can't do anything about this currently, since I cam't get the current theme background color, or can I? Or should the theme icons be used to start with?

**Comment by Depau** [comment]
I have no idea, I can check if VivaldiFox has an API for that.

**Comment by nt1m** [comment]
@freaktechnik seems to be using `theme_icons` which is the correct API for this. However, there's a Firefox bug that prevents this from working correctly: https://bugzilla.mozilla.org/show_bug.cgi?id=1441708

**Comment by freaktechnik** [comment]
Thank you for the input, I'll close this for now then.
