### ISSUE TITLE
Make it compatible with tab containers

### ISSUE THREAD

**Issue by j-a-m-l** [freaktechnik/advanced-github-notifier#86]
This extension always opens the URLs in a default no-containerized tab. Ideally, the user would be able to choose which tab container should be used.

**Comment by freaktechnik** [comment]
I'd suggest using an extension like Multi-Account-Containers for that. I don't think it's a good solution for individual extensions that open tabs to try and offer some way of customizing which container to open links in.

**Comment by j-a-m-l** [comment]
I understand. The problem is that you can't choose it on the Mozilla extension.

Anyway, I've found a way to do it: https://addons.mozilla.org/en-GB/firefox/addon/containerise
