### ISSUE TITLE
Set duration of desktop notifications

### ISSUE THREAD

**Issue by Keith94** [freaktechnik/advanced-github-notifier#9]
Notifications seem to last about 20 seconds, is there a way to configure how long they are displayed for, and also a way to disable them entirely?

**Comment by freaktechnik** [comment]
I can add an option to disable them, however I do not think it's worth the trouble of making the duration configurable. It is in theory possible, but way more complicated than it should be in my opinion.

**Comment by freaktechnik** [comment]
A preference is now implemented for the upcoming version.

**Comment by Keith94** [comment]
Thank you for the quick fix. I will try to get the development version installed somehow.

**Comment by freaktechnik** [comment]
I've uploaded it in the development channel: https://addons.mozilla.org/en-US/firefox/addon/advanced-github-notifier/versions/beta
