### ISSUE TITLE
Add Portuguese translation to Transifex

### ISSUE THREAD

**Issue by FFY00** [freaktechnik/advanced-github-notifier#95]
I would be willing to help translate the extension to Portuguese (pt-PT).

**Comment by freaktechnik** [comment]
I've added the language, please request to join the team for pt_PT.

Thank you for the interest in translating this extension!

**Comment by freaktechnik** [comment]
Sorry, I only just found where the request was located. I don't like how transifex handles the translation requests and only sometimes sends me an email to notify me...
